### ISSUE TITLE
an anon discord user wants a hacked account

### ISSUE THREAD

**Issue by ghost** [ProdigyMobileHaxs/MobileProdigyHaxs#3]
***What items should be in the account?***:
anything works

***What level do you want, how much gold, dark tower floor, etc?***:
100

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:
dck.dachickenking@gmail.com

**Comment by SakuraKitsunee** [comment]
sorry just saw this what deos he/she want on the account

**Comment by SakuraKitsunee** [comment]
@ChickenOnYT 
user: Caleb_The_Slytherinnn

pass: a12345

**Comment by ghost** [comment]
ty
